name: TinkersConstruct-Modern Build

on:
  push:
    branches: ["main"]
#  pull_request:
#    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17 (Temurin as fallback)
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Download and Install JetBrains Runtime (JBR)
      run: |
        JBR_VERSION="17.0.12-b527.4"
        JBR_URL="https://cache-redirector.jetbrains.com/intellij-jbr/jbr-${JBR_VERSION}-linux-x64-b527.4.tar.gz"
        JBR_PATH="$HOME/jbr"
        
        wget -O jbr.tar.gz ${JBR_URL}
        
        mkdir -p ${JBR_PATH}
        tar -xzf jbr.tar.gz -C ${JBR_PATH} --strip-components=1
        
        echo "${JBR_PATH}/bin" >> $GITHUB_PATH

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    
    - name: Build with Gradle
      run: ./gradlew build --info

    - name: Get workflow timestamp
      id: timestamp
      run: echo "TIMESTAMP=$(TZ='Asia/Shanghai' date +'%Y%m%d-%H-%M')" >> $GITHUB_ENV

    - name: Rename JAR
      run: |
        cd build/libs
        for f in *.jar; do
          mv "$f" "${f%.jar}-SNAPSHOT-$TIMESTAMP.jar"
        done
      shell: bash
      
    - name: Upload JAR file
      uses: actions/upload-artifact@v4
      with:
        name: TConstruct-Modern
        path: build/libs/*.jar
        compression-level: 0
